### ISSUE TITLE
Rdpack CI tests failing with rstudioapi 0.17.1 ?

### ISSUE THREAD

**Issue by charles-plessy** [GeoBosh/Rdpack#37] opened 2024-11-15 05:56 UTC
Hello, in Debian we package Rdpack and in our CI test runs, Rdpack `2.6.1` started to fail after we upgraded `rstudioapi` from version `0.17.0` to `0.17.1`.  I see similar failures on CRAN as of today with the following output, which in our case makes the difference between passed and failed.

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-bib.R:90:5'): bib works fine ─────────────────────────────────
`insert_ref("xxx", package = "rbibutils")` did not throw an error.
```

Do you think that this is something to be fixed on your side?

**Comment by GeoBosh** [comment] 2024-11-15 09:01
Thanks for the report.

Indeed, I see the same error on CRAN on some platforms, as well. It is probably not related to the RStudio API since that is used for an add-in only. I will fix it.

**Comment by GeoBosh** [comment] 2024-11-15 10:02
I identified the cause of the error. 

Due to a change in R-devel before the release of R-4.4.2 (a warning message was turned into an error), I released a fix of Rdpack (v2.6.1) which accommodated the change by conditioning  on R > 4.4.1 and R <= 4.4.1. As it turned out they didn't incorporate that R-devel change in R-4.4.2, hence the error.

The above explains why the error showed up only recently, after the release of R-4.4.2.

I presume that you are testing with R-4.4.2?

**Comment by GeoBosh** [comment] 2024-11-15 12:58
Fixed in Rdpack v2.6.2, now on CRAN.

**Comment by charles-plessy** [comment] 2024-11-15 13:03
Thanks for the quick response! In Debian we were in a strange situation where [the error would not show in R-4.4.2 when rstudioapi was still at version 0.17.0](https://lists.debian.org/debian-r/2024/11/msg00002.html), which lead me to suggest a link. I will update Rdpack in Debian and we will see how the CI tests run on our side.

**Comment by eddelbuettel** [comment] 2024-11-15 13:10
Awesome.  (I had alerted @charles-plessy as the failure in r-cran-rdpack prevented r-base itself from migrating.)  For what it is worth I am aware of two other instances of 'expected a chance from r-devel to be in R 4.4.2 but it will be in R 4.5.0' and one of those actually triggered an interim update to r-base too.

Thanks for taking care of it upstream.

**Comment by GeoBosh** [comment] 2024-11-15 14:43
I didn't realise what a major trouble that error has caused.:)

I updated 'rstudioapi' to v0.17.1 but R-4.2.2 was still giving the test error on my system with the previous version of Rdpack. It is possible that 'rstudioapi' masks something.
 In case this pops up in the future, the test concerned is self-contained:
`insert_ref("xxx", package = "rbibutils")`, wrapped in testthat helper functions for the test files in the package:
```
    if(getRversion() <= "4.4.2")
        expect_warning(insert_ref("xxx", package = "rbibutils"))
    else # since R-devel c86938 the warning was changed to error
        expect_error(insert_ref("xxx", package = "rbibutils"))
```
where "4.4.2" was "4.4.1" before the fix and assuming Rdpack and testthat are loaded.

It is a conundrum for me how to reliably handle changes in R-devel. Sometimes I condition on the revision number but I don't believe that that would help for features that are not transferred from R-devel to intermediate R versions.

**Comment by eddelbuettel** [comment] 2024-11-15 15:18
(Just to avoid misunderstanding:  Team Rcpp had a different thinko about '4.4.2 change vs 4.5.0' change, but I mentioned it because it just came in yet another package (and context) and now I don't remember where.  But your issue did not cause our issue.  They were merely coinciding because of 4.4.2  :wink:).

Looking at your code, I think I would use `getRversion() < "4.5.0"` because a possible 4.4.3 would compare higher but be based again on r-patched and R Core may not carry the change over from 'devel' to 'patched'

**Comment by GeoBosh** [comment] 2024-11-15 15:28
Thanks, `getRversion() < "4.5.0"` seems a better bet indeed.

**Comment by eddelbuettel** [comment] 2024-11-15 15:39
It's a "been there, done that" from over the years accomidating the upcoming change next April. Battle-tested.

**Comment by eddelbuettel** [comment] 2024-11-15 15:42
BTW had been meaning to say _Thank you!_ for picking up some of the RMetrics packages and keeping then alive!  Much appreciated.

**Comment by GeoBosh** [comment] 2024-11-15 16:28
Thank you, it is great to feel appreciated!

**Closed** 2024-11-15 21:23 UTC
